# Generated by Django 4.2.17 on 2025-02-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameArticle', models.CharField(blank=True, max_length=128, null=True)),
                ('contentArticle', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTheme', models.CharField(blank=True, max_length=128, null=True)),
                ('descriptionTheme', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
