# Generated by Django 4.2.17 on 2025-02-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiPy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='themeR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiPy.theme'),
        ),
    ]
